/*
  This class has been generated by the Code Generator
*/

package com.dh.excelutilspkg;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;


public class Util extends UtilBase
{
    public Util()
    {
        this((BusObjectConfig)null);
    }

    public Util(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.dh.excelutilspkg.Util> getUtilObjects(com.cordys.cpc.bsf.query.Cursor cursor)
    {
        // TODO implement body
        return null;
    }
    public static int createExcelUsingDataAndTemplate(int dataNode,String businessObject,int excelConfigurationNode,String locationPath,String templateName,String fileName)
    {    	
    	return GenerateExcel.createExcelUsingDataAndTemplate(dataNode, businessObject, excelConfigurationNode, locationPath, templateName, fileName);
    }
    public void onInsert()
    {
    }

    public void onUpdate()
    {
    }

    public void onDelete()
    {
    }

}
